### ISSUE TITLE
[crash bug]When placing modded signs, this mod causes you to crash

### ISSUE THREAD

**Issue by Zunwolf1896** [Magistu/Epic-Knights#12] opened 2023-07-31 15:30 UTC
### Steps to Reproduce

1. Have this mod, Architectury and betterarcheology, blockus, beachparty, regions unexplored, helions sniffer plus installed. 
2. Play your game, find and place a sign from any of the other mods
3. Have your minecraft crash back to launcher with a crash report. 

### Expected Behavior

Place a sign, type on the sign, be happy. 

### Actual Behavior

Place a sign in the world and have your game poof

### Your Minecraft version

1.20.1
Sniffer+-fabric-1.20.1-0.2.0.jar
RegionsUnexploredFabric-0.4.1+1.20.1.jar
[1.20.1-fabric]-Epic-Knights-8.1.jar
architectury-9.1.12-fabric.jar

### Your error log

https://gist.github.com/Zunwolf1896/d9f9be0f491b6d43a4968e5518a46bce
https://gist.github.com/Zunwolf1896/057b2d5ec4fbe62b42b9d237b895e2b6

### Additional Comments

It took a couple hours of testing and trying to figure out what mod was causing this. We figured it had something to do with Supplementaries first, as all the mods with signs where creating a error in the console

Failed to generate hanging sign extension texture for **betterarcheology**:rotten. Could be that the target mod isnt registering their wood type properly
Failed to generate hanging sign extension texture for **blockus:white_oak**. Could be that the target mod isnt registering their wood type properly
Failed to generate hanging sign extension texture for **beachparty:palm**. Could be that the target mod isnt registering their wood type properly
Failed to generate hanging sign extension texture for **blockus:legacy**. Could be that the target mod isnt registering their wood type properly

But after removing supplementaries, we still had the crash so continued to find something else. 

We then figured it was something to do with Terraformer and their terraform-wood-api process, so we went through all the mods whcih used this, removing them one by one, again this did not stop placed signs from crashing us. 

Eventually, removing Archetectury and loading in stopped the crash when placing signs. This narrowed us down to the following mods whci all require archetectury:

Knaves Needs
Simply Swords
Epic Knights Mod
MCPitandLib
Respawn Obelisks

So we went through deleting these 5 mods one by one to see which one it was. 

Last one we tried was this one here, the Epic Knights mod. We removed this, and was able ot place a sign without instanlty being crashed. 

We have also reported this being an issue in the following githubs
https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/11
and
https://github.com/Dariensg/Hellions-Sniffer-Plus/issues/8 

### Conclusion

- [x] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment] 2023-08-11 11:58
@JoostMSoftware , @Zunwolf1896 fixed in v8.2! the problem caused by too early loading of modded sheets

**Comment by JoostMSoftware** [comment] 2023-08-11 12:10
Thanks @Magistu for fixing it so quickly.

**Comment by Magistu** [comment] 2023-08-11 12:36
it was just released. check out the [modpage](https://legacy.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons/files)

**Closed** 2023-08-11 12:36 UTC
Labels: bug
