### ISSUE TITLE
mouseClicked event handler

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [Magistu/Epic-Knights#15] opened 2023-10-07 22:38 UTC
### Steps to Reproduce

1. use this mod
2. use a loom with a flag from supplementaries
3. click an icon on a loom

### Expected Behavior

The flag would have an icon because of the loom

### Actual Behavior

The game automatically saved the world and then crashed

### Your Minecraft version

1.19.2 Forge

### Your error log

https://gist.github.com/mrdiamondmanguydudeman/c7212e8d7db8df59f794480acaf60d51

### Additional Comments

I was using the Supplementaries Mod Flag, I think this mod is the problem but im not sure.

### Conclusion

- [x] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment] 2024-07-22 16:13
duplicate of https://github.com/Magistu/Epic-Knights/issues/35

**Closed by Magistu** 2024-07-22 16:13 UTC
Labels: bug
